server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jianshu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2D8
    username: 123
    password: 123